### ISSUE TITLE
Is it possible to translate the action buttons?

### ISSUE THREAD

**Issue by robmr88** [koji-1009/flutter_auth_ui#42]
Hi, thank you for this awesome library, I was wondering if it was possible to translate the buttons and the labels. I'm working from Italy and when I launch the login the pages appear with all the labels in englis. Woult it be possible to have them in a desired language?
Thank you

**Comment by koji-1009** [comment]
Hi, @robmr88.

Maybe the problem happens on iOS.
Android is fine in my environment.

Could you check the following documents?
Because `flutter_auth_ui` uses native SDK, we need to add some params.
<https://flutter.dev/docs/development/accessibility-and-localization/internationalization#localizing-for-ios-updating-the-ios-app-bundle>

**Comment by robmr88** [comment]
Yes, i forgot to mention it in my question. The issue is only on iOs, in android the labels are translated

**Comment by koji-1009** [comment]
@robmr88 

Has it been fixed as described in the document?
I'm thinking of adding it to the README.

**Comment by robmr88** [comment]
Sorry, I've been working on something else since this post. I will try the solution later today, I'll let you know if it works and the labels in the login/registration flow appear translated.
