### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by jeanmatthieud** [koji-1009/flutter_auth_ui#43]
Hi,

Thanks for your plugin !
It enables me to quickly add user management.

Could it be possible to add a custom logo for the login page ?
On FirebaseUi for Android, it's possible : 
```java
startActivityForResult(
        AuthUI.getInstance()
                .createSignInIntentBuilder()
                .setAvailableProviders(providers)
                .setLogo(R.drawable.my_great_logo)      // Set logo drawable
                .setTheme(R.style.MySuperAppTheme)      // Set theme
                .build(),
        RC_SIGN_IN);
```
[Source](https://firebase.google.com/docs/auth/android/firebaseui#customization)

**Comment by koji-1009** [comment]
Hi @jeanmatthieud.

I haven't added that feature at this time.
We need to think about how to specify the drawable file.

Is it better to add a resource file to the Android directory so that it will be displayed?
`/android/app/src/main/res/drawable/flutter_auth_ui_logo.xml` is an example of what I'm thinking.

**Comment by jeanmatthieud** [comment]
> Is it better to add a resource file to the Android directory so that it will be displayed?
> `/android/app/src/main/res/drawable/flutter_auth_ui_logo.xml` is an example of what I'm thinking.

It could be a good solution ! It works quite well for the colors (as you explained it in the readme file)
