### ISSUE TITLE
Single Auth Provider on IOS not work like Android.

### ISSUE THREAD

**Issue by tunchamroeun** [koji-1009/flutter_auth_ui#77]
I want to call from my custom button. I provided single auth provider for each onPress button, It works well on Android, but on IOS still see single button page.

**Comment by koji-1009** [comment]
Hi @tunchamroeun ,

Sorry, that's the standard behavior of firebaseui-ios.
https://github.com/firebase/FirebaseUI-iOS/issues/295

As far as checking the issue of iOS, even if only the phone is specially supported, there are no plans to support it because it seems that refactoring will be required.
https://github.com/firebase/FirebaseUI-iOS/issues/809
