### ISSUE TITLE
Compatibility issue with FBSDKLoginKit

### ISSUE THREAD

**Issue by ryandailey100** [koji-1009/flutter_auth_ui#79]
I am getting the following error when I try and run my app. 

`CocoaPods could not find compatible versions for pod "FBSDKLoginKit":
      In Podfile:
        flutter_auth_ui (from `.symlinks/plugins/flutter_auth_ui/ios`) was resolved to 2.4.1, which depends on
          FirebaseUI/Facebook (~> 12.0) was resolved to 12.0.2, which depends on
            FirebaseFacebookAuthUI (~> 12.0) was resolved to 12.0.0, which depends on
              FBSDKLoginKit (~> 11.0)

        flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 3.5.3, which depends on
          FBSDKLoginKit (~> 12.0.2)`

I am using the latest version of this library. I ran a flutter pub upgrade and still no luck. I even tried removing the pod lock file and still same issue.

**Comment by ryandailey100** [comment]
Here all all the dependencies I am using:
`
# Firebase
  firebase_auth: ^3.1.5
  firebase_core: ^1.9.0
  firebase_crashlytics: ^2.2.5
  firebase_database: ^8.0.2
  firebase_messaging: ^11.0.0

# Social Auth
  flutter_facebook_auth: "^3.5.6"
  sign_in_with_apple: ^3.2.0
  crypto: ^3.0.1

# UI
  flutter_auth_ui: ^2.4.1
`

**Comment by koji-1009** [comment]
That seems to be happening because the FirebaseUI-iOS specification and the flutter-facebook-auth specification are not suitable.

https://github.com/firebase/FirebaseUI-iOS/blob/v12.1.0/FirebaseFacebookAuthUI/Podfile
https://github.com/darwin-morocho/flutter-facebook-auth/blob/master/facebook_auth/ios/flutter_facebook_auth.podspec

Does it work if I downgrade flutter-facebook-auth to 3.5.2?
https://github.com/darwin-morocho/flutter-facebook-auth/blob/master/facebook_auth/CHANGELOG.md#352
